services:
  gemini-draw:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        VERSION: ${VERSION:-dev}
    image: ghcr.io/kaijen/ai-draw:latest
    env_file: ../.env
    volumes:
      - ..:/app/data
    working_dir: /app/data
    entrypoint: ["gemini-draw"]

  or-draw:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        VERSION: ${VERSION:-dev}
    image: ghcr.io/kaijen/ai-draw:latest
    env_file: ../.env
    volumes:
      - ..:/app/data
    working_dir: /app/data
    entrypoint: ["or-draw"]
